name: build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone build repo
        uses: actions/checkout@v3

      - name: Clone PhotoPrism repo
        run: git submodule update --init

      - name: Build PhotoPrism
        run: BUILD_TAG=${{ github.ref_name }} make build tar.gz

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: photoprism.tar.gz
          body: "Automated build of PhotoPrism version ${{ github.ref_name }}"
          prerelease: false
          draft: false
        env:
          GITHUB_TOKEN: ${{ github.token }}
